-- 1. BERSIHKAN TABEL LAMA (Agar tidak error "already exists")
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS jadwal_posyandu CASCADE;
DROP TABLE IF EXISTS pemeriksaan_anak CASCADE;
DROP TABLE IF EXISTS pemeriksaan_ibu CASCADE;
DROP TABLE IF EXISTS riwayat_kesehatan_ibu CASCADE;
DROP TABLE IF EXISTS anak CASCADE;
DROP TABLE IF EXISTS suami CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- 2. BUAT ULANG TABEL DENGAN STRUKTUR YANG BENAR

-- Tabel Utama: Profiles (Link ke Clerk ID)
create table profiles (
  id text primary key, -- ID ini sama dengan User ID di Clerk
  nik text unique,
  nama_lengkap text,
  username text,
  email text,
  no_telepon text,
  alamat text,
  role text default 'user', -- user, kader, admin
  status text default 'Aktif',
  
  -- Data Identitas Ibu (User)
  jenis_kelamin text,
  no_jkn text,
  faskes text,
  pendidikan_terakhir text,
  pekerjaan text,
  gol_darah text,
  tempat_lahir text,
  tanggal_lahir date,
  asuransi text,
  
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabel Suami
create table suami (
  id bigint generated by default as identity primary key,
  profile_id text references profiles(id) on delete cascade,
  nama_lengkap text,
  nik text,
  jenis_kelamin text default 'Laki-laki',
  alamat text,
  no_telepon text,
  no_jkn text,
  faskes text,
  pendidikan_terakhir text,
  pekerjaan text,
  gol_darah text,
  tempat_lahir text,
  tanggal_lahir date,
  asuransi text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabel Anak
create table anak (
  id bigint generated by default as identity primary key,
  profile_id text references profiles(id) on delete cascade,
  nama_lengkap text,
  nik text,
  jenis_kelamin text,
  anak_ke int,
  no_jkn text,
  tempat_lahir text,
  tanggal_lahir date,
  nama_ibu text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabel Riwayat Kesehatan Ibu
create table riwayat_kesehatan_ibu (
  id bigint generated by default as identity primary key,
  profile_id text references profiles(id) on delete cascade,
  kehamilan_ke int,
  riwayat_keguguran text,
  riwayat_penyakit text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabel Pemeriksaan Ibu (ANC)
create table pemeriksaan_ibu (
  id bigint generated by default as identity primary key,
  ibu_id text references profiles(id) on delete cascade,
  kader_id text references profiles(id),
  tanggal_periksa date,
  usia_kandungan int,
  bb numeric(5,2),
  tensi text,
  tfu numeric(5,2),
  djj int,
  lila numeric(5,2),
  catatan text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabel Pemeriksaan Anak (Tumbuh Kembang)
create table pemeriksaan_anak (
  id bigint generated by default as identity primary key,
  anak_id bigint references anak(id) on delete cascade,
  kader_id text references profiles(id),
  tanggal_periksa date,
  usia_bulan int,
  bb numeric(5,2),
  tb numeric(5,2),
  lk numeric(5,2),
  lila numeric(5,2),
  vitamin_a text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabel Jadwal Posyandu
create table jadwal_posyandu (
  id bigint generated by default as identity primary key,
  nama_kader text,
  tanggal date,
  nama_bidan text,
  kegiatan text,
  kontak text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tabel Notifikasi
create table notifications (
  id bigint generated by default as identity primary key,
  user_id text references profiles(id),
  jenis text,
  ringkasan text,
  status text default 'Pending',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. AKTIFKAN KEAMANAN DATA (RLS)
alter table profiles enable row level security;
alter table suami enable row level security;
alter table anak enable row level security;
alter table riwayat_kesehatan_ibu enable row level security;
alter table pemeriksaan_ibu enable row level security;
alter table pemeriksaan_anak enable row level security;
alter table jadwal_posyandu enable row level security;
alter table notifications enable row level security;

-- Policy Akses Dasar (PENTING: Agar aplikasi bisa baca/tulis)
create policy "Enable all access for authenticated users" on profiles for all to authenticated using (true);
create policy "Enable all access for authenticated users" on suami for all to authenticated using (true);
create policy "Enable all access for authenticated users" on anak for all to authenticated using (true);
create policy "Enable all access for authenticated users" on riwayat_kesehatan_ibu for all to authenticated using (true);
create policy "Enable all access for authenticated users" on pemeriksaan_ibu for all to authenticated using (true);
create policy "Enable all access for authenticated users" on pemeriksaan_anak for all to authenticated using (true);
create policy "Enable all access for authenticated users" on jadwal_posyandu for all to authenticated using (true);
create policy "Enable all access for authenticated users" on notifications for all to authenticated using (true);